# Generated by Django 5.1.4 on 2025-01-29 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grooveguesser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='join_data',
            new_name='join_date',
        ),
    ]
