# Generated by Django 5.1.5 on 2025-02-11 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grooveguesser', '0002_rename_join_data_account_join_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
