# Generated by Django 6.0.dev20250116121251 on 2025-02-06 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grooveguesser', '0002_rename_join_data_account_join_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
