# Generated by Django 5.1.5 on 2025-03-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooveguesser', '0002_rename_join_data_account_join_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('album', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
        # migrations.DeleteModel(
        #     name='Account',
        # ),
    ]
