# Generated by Django 6.0.dev20250116121251 on 2025-02-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grooveguesser', '0003_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='grooveguesser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('body', models.TextField()),
                ('slug', models.SlugField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ImageField(blank=True, default='logo.jpg', upload_to='')),
            ],
        ),
    ]
