# Generated by Django 5.1.5 on 2025-02-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grooveguesser', '0003_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=10)),
                ('score', models.BigIntegerField(blank=0)),
            ],
        ),
    ]
