# Generated by Django 5.1.4 on 2025-03-27 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('grooveguesser', '0003_song_delete_account'),
        ('grooveguesser', '0004_initial'),
    ]

    operations = [
    ]
