# Generated by Django 5.1.4 on 2025-04-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grooveguesser', '0003_song_delete_account'),
        ('grooveguesser', '0005_merge_0003_song_delete_account_0004_initial'),
    ]

    operations = [
    ]
