# Generated by Django 5.1.4 on 2025-04-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooveguesser', '0006_merge_20250405_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='category',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
