# Generated by Django 5.1.5 on 2025-03-07 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
