# Generated by Django 5.1.4 on 2025-04-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Join Date'),
        ),
    ]
